"""added player table

Revision ID: 781e3cd979a2
Revises: 6737c3d1809b
Create Date: 2018-03-26 23:11:08.236510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '781e3cd979a2'
down_revision = '6737c3d1809b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('golfplayers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('given_name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('golfplayers')
    # ### end Alembic commands ###
